import React from "react"

export type UploaderProps = {
    setImage: React.Dispatch<React.SetStateAction<any>>,
    setImageURL: React.Dispatch<React.SetStateAction<string>>,
    imageMaxSize?: number,
    imageMaxWidth?: number,
    imageMaxHeight?: number,
    imageTypes?: string[],
    uploadText?: string,
    uploadIcon?: JSX.Element,
    uploadIconSize?: string,
    uploadIconColor?: string,
    uploadTextColor?: string,
    uploadTextSize?: string,
    uploadTextFontWeight?: string,
    uploadTextFontFamily?: string,
    uploadTextFontStyle?: string,
    borderRadius?: string,
    border?: string,
    borderColor ?: string,
    borderStyle ?: string,
    boxShadow?: string,
}

export type ImageBoxProps = {
    setImage: React.Dispatch<React.SetStateAction<any>>,
    setImageURL: React.Dispatch<React.SetStateAction<any>>,
    imageURL: string,
    imageBoxWidth?: string,
    imageBoxHeight?: string,
    borderRadius?: string,
    border?: string,
    borderColor?: string,
    borderWidth?: string,
    borderStyle?: string,
    boxShadow?: string,
}

export type PackageProps = {
    uploadText?: string,
    uploadIcon?: JSX.Element,
    uploadIconSize?: string,
    uploadIconColor?: string,
    uploadTextColor?: string,
    uploadTextSize?: string,
    uploadTextFontWeight?: string,
    imageBoxWidth?: string,
    imageBoxHeight?: string,
    borderRadius?: string,
    border?: string,
    borderColor?: string,
    borderStyle?: string,
    boxShadow?: string,
    image: any,
    setImage: React.Dispatch<React.SetStateAction<any>>,
    imageURL: string,
    setImageURL: React.Dispatch<React.SetStateAction<any>>,
}